### ISSUE TITLE
Location field removed from info session data 

### ISSUE THREAD

**Issue by sanchitgera** [uWaterloo/api-documentation#78]
The response from `terms/{term_id}/infosessions` and `resources/infosessions` contains a `building` object. As per the documentation, there should a `location` string instead.

**Comment by zainh96** [comment]
From what I understand the response has been updated recently, but the documentation has not. I've updated the documentation and made a pull request - i'm still waiting on the merge to go through.

**Comment by nathanv** [comment]
@KartikTalwar would you be able to take a quick look at this?

**Comment by KartikTalwar** [comment]
hey @sanchitgera as @zainh96 mentioned, a change in the data source led to updating the production version of the endpoint without a lot of warning (we did mention this in the monthly newsletter that went out to all api key holders)

The new changes just add better granularity to the location and audience information along with some date-time standardizations. If you still have any questions about this, I'm happy to answer them here, otherwise please feel free to close the issue

**Comment by sanchitgera** [comment]
@KartikTalwar @zainh96 Sounds good. Just wanted to be sure :) Thanks!
